Switch to osmium

diff --git a/charts/overpass-api-chart/templates/configmap.yaml b/charts/overpass-api-chart/templates/configmap.yaml
--- a/charts/overpass-api-chart/templates/configmap.yaml
+++ b/charts/overpass-api-chart/templates/configmap.yaml
@@ -65,33 +65,33 @@ data:
       fi
 
       if [[ "$planet_file" == *.osm.pbf ]]; then
-        log "INFO" "Converting PBF to OSM format using osmconvert with progress..."
-        local osm_file="${WORK_DIR}/planet.osm"
+        log "INFO" "Converting PBF to OSM format using osmium with progress..."
+        local osm_file="${WORK_DIR}/planet.osm.bz2"
 
-        # Check if osmconvert is available
-        if ! command -v osmconvert >/dev/null 2>&1; then
-          log "ERROR" "osmconvert command not found. Please install osmconvert."
+        # Check if osmium is available
+        if ! command -v osmium >/dev/null 2>&1; then
+          log "ERROR" "osmium command not found. Please install osmium."
           exit 1
         fi
 
         # Use pv to show progress
-        # Run osmconvert and capture its stderr
+        # Run osmium and capture its stderr
         set +e
 
-        stdbuf -oL osmconvert "${planet_file}" -o="${osm_file}" --verbose \
-          2> "${WORK_DIR}/osmconvert_error.log" | \
+        stdbuf -oL osmium cat "${planet_file}" -o="${osm_file}" --verbose \
+          2> "${WORK_DIR}/osmium_error.log" | \
           pv -i 60 --format "%t %p%%\n" > /dev/null
 
-        # Capture the exit status of osmconvert using PIPESTATUS
+        # Capture the exit status of osmium using PIPESTATUS
         exit_status=${PIPESTATUS[0]}
 
         set -e
 
-        # If osmconvert failed, display the error log
+        # If osmium failed, display the error log
         if [ $exit_status -ne 0 ]; then
-          log "ERROR" "osmconvert failed with exit status $exit_status"
-          log "ERROR" "Error output from osmconvert:"
-          cat "${WORK_DIR}/osmconvert_error.log" >&2
+          log "ERROR" "osmium failed with exit status $exit_status"
+          log "ERROR" "Error output from osmium:"
+          cat "${WORK_DIR}/osmium_error.log" >&2
           sleep 5
           exit $exit_status
         fi
